name: text_animator
description: A Flutter Animated Text Package which helps to give life to values that can passed as data to Flutter Text widget or any other value or string receivable widget.
version: 0.0.1
homepage: ''

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: